# Generated by Django 3.0.8 on 2020-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200814_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.IntegerField(default=0),
        ),
    ]
