# Generated by Django 3.0.8 on 2020-09-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_id',
        ),
    ]
