# Generated by Django 3.0.8 on 2020-09-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_remove_statement_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='operation',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
